[package]
name = "szkolenie-rust-2025"
version = "0.0.1"
edition = "2024"
authors = ["Maciej Oliwa <oliwa.maciej@gmail.com>"]
default-run = "hello_world"

[[bin]]
name = "hello_world"
path = "src/hello_world.rs"

[[bin]]
name = "primitive_types"
path = "src/primitive_types.rs"

[[bin]]
name = "compound_types"
path = "src/compound_types.rs"

[[bin]]
name = "string_types"
path = "src/string_types.rs"

[[bin]]
name = "structs"
path = "src/structs.rs"

[[bin]]
name = "enums"
path = "src/enums.rs"

[[bin]]
name = "consts"
path = "src/consts.rs"

[[bin]]
name = "slice_parsing"
path = "src/examples/empty_slice_parsing.rs"

[[bin]]
name = "functions"
path = "src/functions.rs"

[[bin]]
name = "scopes"
path = "src/scopes.rs"

[[bin]]
name = "higher_order_functions"
path = "src/hof.rs"

[[bin]]
name = "traits_impls"
path = "src/traits_impls.rs"

[dependencies]
my_libs = { path = "./libs" }

